/**
 * AuthorClaw Encrypted Vault
 * AES-256-GCM encrypted credential storage
 * Inherited from MoatBot security architecture
 */

import { randomBytes, createCipheriv, createDecipheriv, scryptSync } from 'crypto';
import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';

const ALGORITHM = 'aes-256-gcm';
const SALT_LENGTH = 32;
const IV_LENGTH = 16;
const TAG_LENGTH = 16;
const KEY_LENGTH = 32;

interface VaultData {
  version: number;
  salt: string;
  entries: Record<string, {
    iv: string;
    tag: string;
    ciphertext: string;
  }>;
}

export class Vault {
  private vaultPath: string;
  private data: VaultData | null = null;
  private masterKey: Buffer | null = null;
  private initialized = false;

  constructor(vaultPath: string) {
    this.vaultPath = vaultPath;
  }

  async initialize(): Promise<void> {
    await mkdir(this.vaultPath, { recursive: true });
    const filePath = join(this.vaultPath, 'vault.enc');

    if (existsSync(filePath)) {
      const raw = await readFile(filePath, 'utf-8');
      this.data = JSON.parse(raw);
    } else {
      // Create new vault
      this.data = {
        version: 1,
        salt: randomBytes(SALT_LENGTH).toString('hex'),
        entries: {},
      };
    }

    // Derive master key from environment variable
    let passphrase = process.env.AUTHORCLAW_VAULT_KEY || '';
    if (!passphrase) {
      // Auto-generate a vault key and save to .env for persistence
      const envPath = join(this.vaultPath, '..', '..', '.env');
      if (!existsSync(envPath)) {
        // First run — generate and persist
        const generated = randomBytes(32).toString('hex');
        try {
          await writeFile(envPath, `# Auto-generated by AuthorClaw on first run\nAUTHORCLAW_VAULT_KEY=${generated}\n`);
          passphrase = generated;
          process.env.AUTHORCLAW_VAULT_KEY = generated;
          console.log('  🔑 Generated vault key and saved to .env — your API keys will persist across restarts.');
        } catch {
          console.warn('  ⚠️  WARNING: Could not write .env file.');
          console.warn('     Using a random session key. Vault data will NOT persist across restarts.');
          console.warn('     Set AUTHORCLAW_VAULT_KEY environment variable for production use.');
        }
      } else {
        console.warn('  ⚠️  WARNING: AUTHORCLAW_VAULT_KEY not set (check your .env file).');
        console.warn('     Using a random session key. Vault data will NOT persist across restarts.');
      }
    }
    const effectivePassphrase = passphrase || randomBytes(32).toString('hex');
    this.masterKey = scryptSync(
      effectivePassphrase,
      Buffer.from(this.data!.salt, 'hex'),
      KEY_LENGTH
    );

    this.initialized = true;
  }

  async get(key: string): Promise<string | null> {
    if (!this.initialized || !this.data || !this.masterKey) return null;

    const entry = this.data.entries[key];
    if (!entry) return null;

    try {
      const iv = Buffer.from(entry.iv, 'hex');
      const tag = Buffer.from(entry.tag, 'hex');
      const ciphertext = Buffer.from(entry.ciphertext, 'hex');

      const decipher = createDecipheriv(ALGORITHM, this.masterKey, iv);
      decipher.setAuthTag(tag);

      let decrypted = decipher.update(ciphertext);
      decrypted = Buffer.concat([decrypted, decipher.final()]);

      return decrypted.toString('utf-8');
    } catch {
      return null;
    }
  }

  async set(key: string, value: string): Promise<void> {
    if (!this.initialized || !this.data || !this.masterKey) {
      throw new Error('Vault not initialized');
    }

    const iv = randomBytes(IV_LENGTH);
    const cipher = createCipheriv(ALGORITHM, this.masterKey, iv);

    let encrypted = cipher.update(value, 'utf-8');
    encrypted = Buffer.concat([encrypted, cipher.final()]);

    this.data.entries[key] = {
      iv: iv.toString('hex'),
      tag: cipher.getAuthTag().toString('hex'),
      ciphertext: encrypted.toString('hex'),
    };

    await this.save();
  }

  async delete(key: string): Promise<boolean> {
    if (!this.initialized || !this.data) return false;

    if (this.data.entries[key]) {
      delete this.data.entries[key];
      await this.save();
      return true;
    }
    return false;
  }

  async list(): Promise<string[]> {
    if (!this.data) return [];
    return Object.keys(this.data.entries);
  }

  private async save(): Promise<void> {
    if (!this.data) return;
    const filePath = join(this.vaultPath, 'vault.enc');
    await writeFile(filePath, JSON.stringify(this.data, null, 2));
  }
}
